config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => 'accounts'

  resources :suggestions
  resources :users, only: [:show] do 
    resources :trips, only: [:new, :show, :create, :index] do
      resources :lists, only: [:new, :show, :index, :create] do 
        resources :items, only: [:new, :show, :index, :create]
      end
    end
  end

  get 'pages/home'

  root 'pages#home'

end

app/models/item.rb
class Item < ActiveRecord::Base
  has_and_belongs_to_many :lists
  has_and_belongs_to_many :items
  has_and_belongs_to_many :suggestions
  

  enum item_type: [:Toiletries, :Clothing, :Misc]

  def add_to_list(item, list, suggestion)
  	unless list.items.include?(item)
      list.items << item
      suggestion.items << item
    end
  end
  
  def add_to_preset(item, suggestion, prepared)
  count = 0
    suggestion.items.each do |item|
      if item.name == item.name
        count+=1
      end
    end
    if count >= 5
      unless prepared.items.include?(item)
        prepared.items << item
      end
    end
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :trip
  has_and_belongs_to_many :items
end

app/models/prepared.rb
class Prepared < ActiveRecord::Base
  has_and_belongs_to_many :items
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
  has_and_belongs_to_many :items
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :lists
  has_many :items

  enum trip_type: [:Festival, :Hotel, :Camping, :Friends]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :trips
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
  	@user = current_user
  	@trip = Trip.find(params[:trip_id])  	
  end

  def create 
    @user = current_user	
    @trip = Trip.find(params[:trip_id])
    @list = List.find(params[:list_id])
    @suggestion = Suggestion.find_by(name: @trip.trip_type)
    @prepared = Prepared.find_by(name: @trip.trip_type)
    @item = Item.new(item_params)
    @item = Item.where(name: @item.name).first_or_create(item_params)
    @item.add_to_list(@item, @list, @suggestion)
    @item.add_to_preset(@item, @suggestion, @prepared)
  	if @item.save
  	  redirect_to user_trip_list_path(@user, @trip, @list)
  	else
  	  render @list
  	end
  end

  private

  def item_params
  	params.require(:item).permit(:name, :item_type, :amount)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def show
    @user = current_user
  	@trip = Trip.find(params[:trip_id])
  	@list = List.find(params[:id])
  	@item = @list.items.new
    @suggestion = Suggestion.find_by(name: @trip.trip_type)
    @prepared = Prepared.find_by(name: @trip.trip_type)
  end

  def new
  	@trip = Trip.find(params[:trip_id])
  	@list = @trip.lists.new
  end

  def create
    @user = current_user
  	@trip = Trip.find(params[:trip_id])
  	@list = @trip.lists.new(list_params) 
  	  if @list.save
  	  	redirect_to user_trip_list_path(@user, @trip, @list)
  	  else
  	    render @trip
  	end
  end

  private

  def list_params
  	params.require(:list).permit(:owner)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  def show
  	@suggestion = Suggestion.find(params[:id])
  end

  def new 
  	@suggestion = Suggestion.new
  end

  def create
  	@suggestion = Suggestion.new
  	@suggestion = Suggestion.create
  end

  private
  def suggestion_params
  	params.require(:suggestion).permit(:name)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  
  def show 
    @user = current_user
    @trip = Trip.find(params[:id])
    trip_type = @trip.trip_type
    @list = @trip.lists.new
    @suggestion = Suggestion.find_by(name: @trip.trip_type)
  end

  def index
  	@user = current_user
  	@trips = @user.trips
  end

  def new
    @user = current_user
  	@trip = Trip.new
  end

  def create
    @user = current_user
    @trip = @user.trips.new(trip_params)
      if @trip.save
        redirect_to user_trip_path(@user, @trip)
      else
        render 'new'    
      end
  end

  private

  def trip_params
  	params.require(:trip).permit(:location, :length, :trip_type)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = current_user
  	@trips = @user.trips
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/change_trip_id_to_list_id_in_items_helper.rb
module ChangeTripIdToListIdInItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/items/new.html.erb
<%= @trip.trip_type %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Packing</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user.present? %>  
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    <%= link_to("#{current_user.email}", user_path(current_user)) %>
  <% else %>
    <%= link_to('Login', new_user_session_path) %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/lists/show.html.erb
<p><%= @list.owner %></p>

<ul>
  <% @list.items.each do |item| %>
    <li><%= item.name %></li>
  <% end %>	
</ul>

<h2>Suggestions for <%= @trip.trip_type %></h2>
<% if @suggestion %>
  <% if @suggestion.items %>
    <% @suggestion.items.each do |item| %>
     <p> <%= item.name %></p>
      <% end %>
  <% end %>
<% end %>

<h2>Prepared list for <%= @trip.trip_type %></h2>
<% if @prepared %>
<% if @prepared.items %>
  <% @prepared.items.each do |item| %>
    <span><%= item.name %></span>
  <% end %>
<% end %>
<% end %>



<%= form_for  ([@user, @trip, @list, @item]) do |f| %>
  
  <div class="field">
  	<%= f.label :name %>
  	<%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :item_type %>
    <%= f.select :item_type, Item.item_types.keys.to_a, include_blank: true %>
  </div>

  <div class="actions">
  	<%= f.submit %>
  </div>

<% end %>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<% if current_user %>
  <p><%= current_user.email %></p>
<% else %>
  <%= link_to "create", new_user_registration_path %>
<% end %>

app/views/trips/new.html.erb
<%= form_for [@user, @trip] do |f| %>
  <div class="field">
  	<%= f.label :location %>
  	<%= f.text_field :location %>
  </div>

  <div class="field">
  	<%= f.label :how_many_days? %>
  	<%= f.number_field :length %>
  </div>

   <div class="field">
    <%= f.label :type_of_trip %>
    <%= f.select :trip_type, Trip.trip_types.keys.to_a, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit "Create Trip" %>
  </div>

<% end %>

app/views/trips/show.html.erb
<% if @suggestion %>
  <p><%= @suggestion.name %></p>
<% end %>
  
<%= form_for ([@user, @trip, @list]) do |f| %>
  <div class="field">
  	<%= f.label :owner %>
  	<%= f.text_field :owner %>
  </div>

  <div class="actions">
  	<%= f.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
<p><%= @user.email %></p>

<%= link_to "New Trip", new_user_trip_path(@user) %>